[package]
name = "sfontplayer"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/sevonj/sfontplayer"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# -- GUI
egui = "0.28"                                                   # GUI
eframe = { version = "0.28", features = ["persistence"] }       # Framework
egui_extras = { version = "0.28", features = ["all_loaders"]}   # Extra gui components
rfd = "0.15"                                                    # File dialog

# -- Persistence
serde = { version = "1", features = ["derive"] }    # Remember app state

# -- Audio
rodio = "0.19"      # Audio
rustysynth = "1.3"  # midi

# -- Misc
rand = "0.8.5"
build-info = "0.0.38"   # For dependency listing

[build-dependencies]
build-info-build = "0.0.38" # For dependency listing
