[package]
name = "jyls_sfont_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.28", features = ["persistence"] }
egui_extras = "0.28"
rfd = "0.15"
rodio = "0.19.0"
rustysynth = "1.3"
serde = { version = "1", features = ["derive"] }

