[package]
name = "sfontplayer"
version = "0.4.1"
edition = "2021"
repository = "https://github.com/sevonj/sfontplayer"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# -- GUI
eframe = { version = "0.29", features = ["persistence"] }       # GUI Framework
egui_extras = { version = "0.29", features = ["all_loaders"]}   # Extra gui components
rfd = "0.15"                                                    # File dialog
egui-notify = { git = "https://github.com/ItsEthra/egui-notify.git", commit = "2fbf8da60f8775499beccbe59ed0df47fee47079" } # toasts

# -- Persistence
serde = { version = "1", features = ["derive"] }    # Remember app state
serde_repr = "0.1"

# -- Audio
rodio = "0.19"      # Audio
rustysynth = "1.3"  # midi

# -- Misc
rand = "0.8.5"
build-info = "0.0.38"   # For dependency listing
walkdir = "2.5"
size_format = "1.0.2"   # File sizes into string

[build-dependencies]
build-info-build = "0.0.38" # For dependency listing
