[package]
name = "sfontplayer"
version = "0.9.0"
edition = "2021"
repository = "https://github.com/sevonj/sfontplayer"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# -- GUI
eframe = { version = "0.29", features = ["persistence"] } # GUI Framework
egui_extras = { version = "0.29", features = [
    "all_loaders",
] } # Extra gui components
rfd = "0.15" # File dialog
egui-notify = { git = "https://github.com/ItsEthra/egui-notify.git", rev = "2fbf8da" } # toasts

# -- Persistence
serde = { version = "1", features = ["derive"] } # Remember app state
serde_repr = "0.1"

# -- Audio
rodio = "0.20"     # Audio
rustysynth = "1.3" # midi

# -- Misc
rand = "0.8"
build-info = "0.0.39" # For dependency listing
walkdir = "2.5"
size_format = "1.0"   # File sizes into string
open = "5.3"          # Open path in file exprorer
anyhow = "1.0"        # Errors
souvlaki = "0.7"      # Media control/metadata system integration
serde_json = "1.0"
directories = "5.0"
relative-path = "1.9.3"

[build-dependencies]
build-info-build = "0.0.38" # For dependency listing

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
nursery = { level = "deny", priority = 0 }
pedantic = { level = "deny", priority = 1 }
enum_glob_use = { level = "deny", priority = 2 }
module_name_repetitions = { level = "allow", priority = 3 }
cast_precision_loss = { level = "allow", priority = 4 }
cast_possible_truncation = { level = "allow", priority = 5 }
cast_sign_loss = { level = "allow", priority = 6 }
out_of_bounds_indexing = { level = "allow", priority = 7 }
perf = { level = "warn", priority = 8 }
style = { level = "warn", priority = 9 }
unwrap_used = { level = "deny", priority = 10 }
# expect_used = { level = "deny", priority = 11 }
struct_excessive_bools = { level = "allow", priority = 12 }
