[package]
name = "jyls_sfont_tool"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/sevonj/sfontplayer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# -- GUI
eframe = { version = "0.28", features = ["persistence"] }   # Framework, gui
egui_extras = "0.28"                                        # Extra gui components
rfd = "0.15"                                                # File dialog

# -- Persistence
serde = { version = "1", features = ["derive"] }    # Remember app state

# -- Audio
rodio = "0.19"      # Audio
rustysynth = "1.3"  # midi
rand = "0.8.5"
