name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format check
      run: cargo fmt -v --check
    - name: Lint
      run: cargo clippy --no-deps --  --deny warnings
      
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install -y alsa-lib-devel
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
