name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  static-checks:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format check
      run: cargo fmt -v --check
      
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install -y libasound2-dev gcc-mingw-w64-x86-64 libdbus-1-dev pkg-config
    - name: Add targets
      run: rustup target add x86_64-unknown-linux-gnu && rustup target add x86_64-pc-windows-gnu

    - name: Build Linux
      run: cargo build --verbose --target=x86_64-unknown-linux-gnu
    - name: Build Windows
      run: cargo build --verbose --target=x86_64-pc-windows-gnu
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --no-deps --  --deny warnings

  coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt install -y libasound2-dev gcc-mingw-w64-x86-64 libdbus-1-dev pkg-config
          cargo install cargo-tarpaulin

      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false
